version: '2'
services:
    myapp:
        container_name: "varjo-resources-api"
        image: varjo-resources:latest
        environment:
            - NODE_ENV=development
        ports:
            - 3000:3000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:4.0
        container_name: "mongodb"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=varjo
          - MONGO_INITDB_ROOT_PASSWORD=resources
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/stdout